version: 0.1.0.{build}

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAURL: http://www.lua.org/ftp
  LUAROCKS_URL: http://keplerproject.github.io/luarocks/releases
  LUAROCKS_REPO: http://rocks.moonscript.org
  LUAROCKS_VER: HEAD #2.2.1
  LUAROCKS_SHORTV: 2.2

  #LUA: the Lua interpreter. either Lua or LuaJIT

  DOWNLOADER: appveyor DownloadFile
  SEVENZIP: 7z

  matrix:
  - LUA_VER: 5.1.5
    LUA_SHORTV: 5.1
    LUA: lua

  - LUA_VER: 5.2.4
    LUA_SHORTV: 5.2
    LUA: lua

  - LUA_VER: 5.3.0
    LUA_SHORTV: 5.3
    LUA: lua

  - LJ_VER: 2.0.3
    LUA_SHORTV: 5.1
    LJ_SHORTV: 2.0
    LUA: luajit

  - LJ_VER: 2.1
    LUA_SHORTV: 5.1
    LJ_SHORTV: 2.1
    LUA: luajit

init:
# Make VS 2013 command line tools available
- call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

install:
# Setup Lua development/build environment
- call .scripts\install_lua.bat

before_build:
#- echo "Installing external deps"

build_script:
- luarocks make

before_test:
# Install test only deps
- luarocks install busted
- luarocks install dromozoa-utf8

test_script:
- busted
